# Generated by Django 3.1.5 on 2021-06-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythagoras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartdesire',
            old_name='hearth_desire_number',
            new_name='heart_desire_number',
        ),
    ]
