# Generated by Django 3.1.5 on 2021-06-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythagoras', '0002_auto_20210628_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeartDesire',
            new_name='HearthDesire',
        ),
        migrations.RenameField(
            model_name='hearthdesire',
            old_name='heart_desire_number',
            new_name='hearth_desire_number',
        ),
        migrations.RenameField(
            model_name='legacypath',
            old_name='active_number',
            new_name='legacy_number',
        ),
    ]
