# Generated by Django 3.2.3 on 2021-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythagoras', '0004_expressionpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activepath',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='destinypath',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expressionpath',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hearthdesire',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='legacypath',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lifepath',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='personality',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='powerpath',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='activepath',
            name='id',
        ),
        migrations.RemoveField(
            model_name='destinypath',
            name='id',
        ),
        migrations.RemoveField(
            model_name='expressionpath',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hearthdesire',
            name='id',
        ),
        migrations.RemoveField(
            model_name='legacypath',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lifepath',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='id',
        ),
        migrations.RemoveField(
            model_name='powerpath',
            name='id',
        ),
        migrations.AlterField(
            model_name='activepath',
            name='active_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='destinypath',
            name='destiny_path_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='expressionpath',
            name='expression_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hearthdesire',
            name='hearth_desire_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='legacypath',
            name='legacy_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lifepath',
            name='life_path_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='personality_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='powerpath',
            name='power_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
