# Generated by Django 3.2.3 on 2021-07-28 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythagoras', '0005_auto_20210720_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifepath',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
