# Generated by Django 3.2.3 on 2021-08-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythagoras', '0008_auto_20210806_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyclepath',
            options={'verbose_name': 'CHỈ SỐ CHU KỲ', 'verbose_name_plural': '3 GIAI ĐOẠN CỦA CUỘC ĐỜI'},
        ),
        migrations.AlterModelOptions(
            name='pyramidpath',
            options={'verbose_name': 'CHỈ SỐ CHẶNG', 'verbose_name_plural': '4 ĐỈNH CAO CUỘC ĐỜI'},
        ),
    ]
