# Generated by Django 3.2.7 on 2021-09-27 16:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythagoras', '0009_auto_20210807_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifepath',
            name='lp_challenge',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Challenge'),
        ),
        migrations.AddField(
            model_name='lifepath',
            name='lp_environment',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Environments'),
        ),
        migrations.AddField(
            model_name='lifepath',
            name='lp_improve',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Improvements'),
        ),
        migrations.AddField(
            model_name='lifepath',
            name='lp_strong',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Strong Points'),
        ),
    ]
